### ISSUE TITLE
Does your workflow work with macOS Sierra?

### ISSUE THREAD

**Issue by josefglatz** [dgo-/alfred-vpn#1]
All Alfred workflow's so far doesn't work since I've udpated to macOS Sierra (not High Sierra)

**Comment by elyase** [comment]
yes.

**Comment by carceneaux** [comment]
I'm currently using this workflow successfully with MacOs Catalina.

**Comment by dgo-** [comment]
Hi, sorry for not answering your question. I don't get an notification. 

The workflow works also in macOS Sierra.
